name: Build
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  rustfmt:
    name: Formatting check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: stable
          components: rustfmt
    - name: Run cargo fmt
      run: cargo fmt -- --check

  clippy:
    name: Analyzing code with Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: stable
          components: clippy
    - name: Run cargo clippy
      run: cargo clippy --all-targets --all-features --workspace -- -D warnings

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: stable
    - name: Run tests
      run: cargo test --workspace --verbose
